# Generated by Django 5.0.7 on 2024-07-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ingrediants', models.TextField(max_length=2000)),
                ('method', models.TextField(max_length=2000)),
                ('source', models.URLField(max_length=256)),
            ],
        ),
    ]
